// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd0HsUU0YnQGXh0O_aBXJ9zMklM5PWIE4',
    appId: '1:622667877844:web:0fc3d7eb83b6da69d55a41',
    messagingSenderId: '622667877844',
    projectId: 'tanako-66',
    authDomain: 'tanako-66.firebaseapp.com',
    storageBucket: 'tanako-66.firebasestorage.app',
    measurementId: 'G-L7N0LK5F03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOW0655OR1oWM6dJt-OAUwbAOdcPEo82E',
    appId: '1:622667877844:android:e1bef913f1efb90fd55a41',
    messagingSenderId: '622667877844',
    projectId: 'tanako-66',
    storageBucket: 'tanako-66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOC0K58XUtkYkiu4_96swcBLx5I1RxB5A',
    appId: '1:622667877844:ios:de1391dbb10cfc05d55a41',
    messagingSenderId: '622667877844',
    projectId: 'tanako-66',
    storageBucket: 'tanako-66.firebasestorage.app',
    iosBundleId: 'com.example.sportShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOC0K58XUtkYkiu4_96swcBLx5I1RxB5A',
    appId: '1:622667877844:ios:de1391dbb10cfc05d55a41',
    messagingSenderId: '622667877844',
    projectId: 'tanako-66',
    storageBucket: 'tanako-66.firebasestorage.app',
    iosBundleId: 'com.example.sportShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd0HsUU0YnQGXh0O_aBXJ9zMklM5PWIE4',
    appId: '1:622667877844:web:660ee91dc258f1fad55a41',
    messagingSenderId: '622667877844',
    projectId: 'tanako-66',
    authDomain: 'tanako-66.firebaseapp.com',
    storageBucket: 'tanako-66.firebasestorage.app',
    measurementId: 'G-TNRMLJ7LSB',
  );
}
